Update search-suggestion-raw with 232 new terms
18F/cv_faq pull request #1188
Opened 2020-11-10 21:54 UTC by debjudy

Update search-suggestion-raw with 232 new terms

Please confirm the following steps are completed:

* [ ] Choose the appropriate target branch:
  * Content
    * `preview` (approved content) <- *Content branch*
    * `main` (production) <- `preview`
* [ ] Assign an appropriate reviewer:
  * *Content admin* or *Project lead* for merge to `preview` (approved content)
  * *Engineer* for merge to master (production)

:sunglasses: [PREVIEW URL]()

2020-11-10 21:56 UTC, debjudy commented
Spurious htmlproofer failure

2020-11-10 22:26 UTC, jonadecker requested changes
Some dupes, some questions

2020-11-10 23:49 UTC, debjudy commented
Spurious htmlproofer...again.

2020-11-11 00:14 UTC, jonadecker commented on suggestions-raw.json
> +  "fema assistance",
Adjacent dupes

2020-11-11 00:14 UTC, jonadecker commented on suggestions-raw.json
> +  "fever temperature",
Split by one dupe

2020-11-11 00:15 UTC, jonadecker commented on suggestions-raw.json
> +  "first case",
Dupe

2020-11-11 00:16 UTC, jonadecker commented on suggestions-raw.json
> +  "food assistance",
dupe

2020-11-11 00:37 UTC, jonadecker commented
Let's mob on this @debjudy and see what's going on

2020-11-11 19:39 UTC, debjudy commented
@jonadecker hoping the 6th time is the charm.  Let me know if you see more dupes.

2020-11-12 15:50 UTC, jonadecker approved these changes
👍

2020-11-12 15:51 UTC, merged